# Generated by Django 4.2.7 on 2023-11-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objavlenia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
